version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  run01:
    cmds:
      - |
        poetry run python \
            src/try_selenium/run01.py

  run02:
    cmds:
      - mkdir dist/
      - |
        poetry run python \
            src/try_selenium/run02.py
    ignore_error: true


  r6:
    cmds:
      - poetry run python src/try_selenium/run06.py

  r5:
    cmds:
      - poetry run python src/try_selenium/run05.py

  r4:
    cmds:
      - |
        poetry run python \
            src/try_selenium/run04.py


  help:
    cmds:
      - poetry run python -m selenium --help

  poetry:
    aliases: [ 'p', 'pm' ]
    cmds:
      - poetry {{.CLI_ARGS}} # install, update

  install:
    aliases: [ 'i' ]
    cmds:
      - poetry install
      - which python
      - poetry python -V

  h:
    cmds:
      - poetry env info
      - poetry env list

  add:
    aliases: [ 'a' ]
    cmds:
      - poetry add {{.CLI_ARGS}} # --dev

  add:all:
    cmds:
      - poetry add "typer[all]" selenium
