[tool.poetry]
name = "try-flet"
version = "0.1.0"
description = ""
authors = ["Henry.Huang <hhglory@outlook.com>"]
readme = "README.md"
packages = [{include = "try_flet", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
flet = "^0.14.0"
loguru = "^0.7.2"
typer = {extras = ["all"], version = "^0.9.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
