version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  pkg:
    aliases: [ "pm" ]
    cmds:
      - rye {{ .CLI_ARGS }}
    dir: flet-template/


  dev:
    aliases: [ 'd' ]
    cmds:
      - rye run dev
    dir: ./flet-template/

  run:app:
    aliases: [ 'ra' ]
    cmds:
      - rye run app
    dir: ./flet-template/

  run:web:
    aliases: [ 'rw' ]
    cmds:
      - rye run web
    dir: ./flet-template/

  build:macos:
    aliases: [ 'bm', ]
    cmds:
      - rye run build-macos
      - open build/macos/
    dir: ./flet-template/

  build:android:
    aliases: [ 'ba', ]
    cmds:
      - rye run build-android
    dir: ./flet-template/

  build:web:
    aliases: [ 'bw', ]
    cmds:
      - rye run build-web
    dir: ./flet-template/

  serve:web:
    aliases: [ 'sw', ]
    cmds:
      - rye run serve-web
    dir: ./flet-template/

  release:
    aliases: [ 'rel' ]
    cmds:
      - rye run flet pack --help
      - |
        rye run flet pack main.py
          --verbose \
          --name pyApp \
          --product-version 0.1.0 \
          --company-name "TryBetterApp" \
          --codesign-identity "com.trybetterapp" \
          --bundle-id "com.trybetterapp.pyapp" \
    dir: ./case01

  new:
    cmds:
      - rye run flet create --help
      - rye run flet create --verbose --template counter --project-name demo demo
