version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  pkg:
    cmds:
      - rye {{ .CLI_ARGS }}

  run:template:
    aliases: [ 'rt' ]
    cmds:
      - rye run flet run src/flet_template/main.py
    dir: ./flet-template/

  run:web:
    aliases: [ 'rw' ]
    cmds:
      - rye run flet run --web src/flet_template/main.py
    dir: ./flet-template/

  build:macos:
    aliases: [ 'bm', ]
    cmds:
      - rye run build-macos
    dir: ./flet-template/

  build:android:
    aliases: [ 'ba', ]
    cmds:
      - rye run build-android
    dir: ./flet-template/

  build:web:
    aliases: [ 'bw', ]
    cmds:
      - rye run build-web
    dir: ./flet-template/


  release:
    aliases: [ 'rel' ]
    cmds:
      - rye run flet pack --help
      - |
        rye run flet pack main.py
          --verbose \
          --name pyApp \
          --product-version 0.1.0 \
          --company-name "TryBetterApp" \
          --codesign-identity "com.trybetterapp" \
          --bundle-id "com.trybetterapp.pyapp" \
    dir: ./case01

  new:
    cmds:
      - rye run flet create --help
      - rye run flet create --verbose --template counter --project-name demo demo
