version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  install:
    aliases: [ "i" ]
    cmds:
      - poetry install

  pkg:
    cmds:
      - poetry {{ .CLI_ARGS }}

  add:
    cmds:
      - poetry add flet loguru "typer[all]"

  run:demo:
    aliases: [ 'rd' ]
    cmds:
      - poetry run flet run .
    dir: ./demo

  rel:macos:
    cmds:
      - flet build macos

  release:
    aliases: [ 'rel' ]
    cmds:
      - poetry run flet pack --help
      - |
        poetry run flet pack main.py
          --verbose \
          --name pyApp \
          --product-version 0.1.0 \
          --company-name "TryBetterApp" \
          --codesign-identity "com.trybetterapp" \
          --bundle-id "com.trybetterapp.pyapp" \
    dir: ./demo

  help:
    cmds:
      - poetry run flet --help

  new:
    cmds:
      - poetry run flet create --help
      - poetry run flet create --verbose --template counter --project-name demo demo
