version: "3"

includes:
  gemini:
    aliases: [ "g", "ge" ]
    taskfile: try-gemini/
    dir: try-gemini/
    optional: true

  chroma:
    taskfile: try-chroma/
    dir: try-chroma/
    optional: true

  autogpt:
    taskfile: try-autogpt/
    dir: try-autogpt/
    optional: true

  spacy:
    taskfile: try-spacy/
    dir: try-spacy/
    optional: true

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  poetry:
    aliases: [ 'p' ]
    cmds:
      - poetry {{.CLI_ARGS}} # install, update
