version: "3"

includes:
  flet:
    aliases: [ "f", "fl" ]
    taskfile: try-flet/
    dir: try-flet/
    optional: true

  kivy-basic:
    aliases: [ "kb" ]
    taskfile: try-kivy/kivy-basic/
    dir: try-kivy/kivy-basic/
    optional: true

  beeware:
    aliases: [ "bw" ]
    taskfile: try-beeware/
    dir: try-beeware/
    optional: true

  pyside:
    aliases: [ "ps", "p" ]
    taskfile: try-pyside/
    dir: try-pyside/
    optional: true

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  install:
    cmds:
      - poetry install

  add:
    cmds:
      - poetry add click discord.py

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve
