version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  run01:
    cmds:
      - |
        poetry run python \
            src/try_playwright/run01.py

  # geo = shanghai
  gen:
    cmds:
      - |
        poetry run python \
          -m playwright codegen \
          --target python \
          --device "iPhone 11" \
          --viewport-size  "1280, 720" \
          --geolocation "31.224361, 121.469170" \
          -o 'src/try_playwright/run02.py' \
          -b chromium \
          https://www.twitter.com


  help:
    cmds:
      - poetry run python -m playwright codegen --help

  poetry:
    aliases: [ 'p' ]
    cmds:
      - poetry {{.CLI_ARGS}} # install, update

  install:
    cmds:
      - poetry install

  add:
    aliases: [ 'a' ]
    cmds:
      - poetry add {{.CLI_ARGS}}

  add:all:
    cmds:
      - poetry add "typer[all]" playwright

  i:
    cmds:
      - poetry run playwright install
