[project]
name = "try-binance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "binance-connector>=3.12.0",
    "binance-futures-connector>=4.1.0",
]
