version: "3"

tasks:
  uv:
    aliases: ["pm", "pkg"]
    cmds:
      - uv {{.CLI_ARGS}}

  run:
    aliases: ["r"]
    cmds:
      - uv sync --all-packages --upgrade
      - uv run {{.CLI_ARGS}}
    dir: src/
