version: "3"

includes:
  py101:
    taskfile: packages/py-101/
    dir: packages/py-101/
    optional: true

  ai:
    taskfile: packages/py-ai/
    dir: packages/py-ai/
    optional: true

  quant:
    aliases: [ 'trade' ]
    taskfile: packages/py-quant/
    dir: packages/py-quant/
    optional: true

  gui:
    aliases: [ 'ui' ]
    taskfile: packages/py-gui/
    dir: packages/py-gui/
    optional: true

  try:
    aliases: [ 't' ]
    taskfile: packages/py-try/
    dir: packages/py-try/
    optional: true




################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################

tasks:
  setup:
    cmds:
      - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
      - pyenv install 3.9.9
      - pyenv virtualenv 3.9.9 py39-toolbox
      - pyenv local py39-toolbox
      - pip install --upgrade pip
      - pip install -U pipx
      - pipx ensurepath
      - pipx --version

  #
  # fix: https://stackoverflow.com/questions/43067039/pyinstaller-error-oserror-python-library-not-found-libpython3-4mu-so-1-0-lib
  #
  install:py:
    cmds:
      - env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.10.6 # fix for pyinstaller

  install:pdm:
    cmds:
      #      - curl -sSL https://pdm-project.org/install-pdm.py | python3 -
      #      - brew install pdm  # 不要用, 会额外装一堆大便进来!
      #      - pip install --user pdm
      - pip install pipx       # 基于 pyenv
      - pipx install pdm[all]  # 基于 pyenv
      - pdm --version

  install:rye:
    cmds:
      - curl -sSf https://rye-up.com/get | bash  # set shell env: export PATH="$HOME/.rye/bin:$PATH"
      - rye --version

  install:poetry:
    cmds:
      - curl -sSL https://install.python-poetry.org | python3 -
      #      - pipx install poetry
      - poetry --version
      - poetry config virtualenvs.in-project true
      - poetry config --list

  install:poetry:clean:
    cmds:
      - curl -sSL https://install.python-poetry.org | python3 - --uninstall
      - curl -sSL https://install.python-poetry.org | python3 -
      - poetry --version

  install:tools:
    cmds:
      - pipx install cookiecutter
      - cookiecutter --version
      - task: install:poetry

  install:
    cmds:
      - pip3 install -r requirements.txt

  install:dev:
    cmds:
      - pip3 install -r requirements-dev.txt

  init:
    cmds:
      - task init:env
      - task install

  init:env:
    cmds:
      - cp .env.local .env

  ##################################################################################################

  # usage:
  #   - task n -- py-try/try-jieba
  n:
    cmds:
      - poetry new {{.CLI_ARGS}} --src
    dir: packages/

  new:
    cmds:
      - echo new ${NEW_PROJECT_DIR}${NEW_PROJECT_NAME}
      - rye init ${NEW_PROJECT_DIR}${NEW_PROJECT_NAME}
      #- cd ${NEW_PROJECT_DIR}; rye init ${NEW_PROJECT_NAME}
    dir: packages/

  new:plugin: # rust plugin
    cmds:
      - echo new ${NEW_PROJECT_DIR}${NEW_PROJECT_NAME}
      - rye init ${NEW_PROJECT_DIR}${NEW_PROJECT_NAME} --build-system maturin
      #- cd ${NEW_PROJECT_DIR}; rye init ${NEW_PROJECT_NAME}
    dir: packages/

  new3:
    dir: packages
    cmds:
      - cookiecutter gh:jacebrowning/template-python -f

  new4:
    cmds:
      - pdm init --copier gh:pawamoy/copier-pdm --UNSAFE
    dir: packages/

  ##################################################################################################

  quick:
    aliases: [ 'q' ]
    cmds:
      - task: cc
      - task: push

  cc:
    cmds:
      - task: commit
      - task: commit

  commit:
    aliases: [ 'c' ]
    cmds:
      - git add .
      - git commit -m "update"
    ignore_error: true

  pull:
    cmds:
      - git config pull.rebase false
      - git pull origin main

  push:
    cmds:
      - git push origin main --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git" '{print "https://github.com/"$1}'`; open $repo_url
