version: "3"

includes:
  dev:
    taskfile: Taskfile.dev.yml
    dir: .
    optional: true

  py101:
    taskfile: packages/py-101/
    dir: packages/py-101/
    optional: true

  ai:
    taskfile: packages/py-ai/
    dir: packages/py-ai/
    optional: true

  auto:
    taskfile: packages/py-automation
    dir: packages/py-automation
    optional: true

  quant:
    aliases: ["trade", "qt"]
    taskfile: packages/py-quant/
    dir: packages/py-quant/
    optional: true

  chart:
    aliases: ["ch"]
    taskfile: packages/py-chart/
    dir: packages/py-chart/
    optional: true

  gui:
    aliases: ["ui"]
    taskfile: packages/py-gui/
    dir: packages/py-gui/
    optional: true

  crawler:
    aliases: ["cr"]
    taskfile: packages/py-crawler/
    dir: packages/py-crawler/
    optional: true

  data:
    aliases: ["da", "data-analysis", "big-data", "data-science"]
    taskfile: packages/py-data/
    dir: packages/py-data/
    optional: true

  try:
    aliases: ["t", "tr"]
    taskfile: packages/try/
    dir: packages/try/
    optional: true

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################

tasks:
  init:
    cmds:
      - task: init:env
      - task: install

  install:
    aliases: ["i"]
    cmds:
      # - uv sync
      # - uv sync --group=dev
      # - uv sync --group=docs
      - uv sync --all-packages --upgrade

  init:env:
    cmds:
      - cp .env.local .env

  uv:
    aliases: ["pkg", "pm"]
    cmds:
      - uv {{.CLI_ARGS}}

  sync:
    cmds:
      - uv self update
      - uv sync --all-packages --upgrade
    ignore_error: true

  ##################################################################################################

  docs:
    cmds:
      - task: sync
      - uv run mkdocs serve --open --watch=docs --watch=mkdocs.yml --dev-addr=localhost:5002

  docs:deploy:
    aliases: ["docs:d"]
    cmds:
      - task: sync
      - uv run mkdocs gh-deploy # build and create gh-pages branch
      - git push origin gh-pages:gh-pages --force # push to public repo

  ##################################################################################################

  # usage:
  #   - task n -- try/try-jieba
  new:
    aliases: ["n"]
    cmds:
      - uv init {{.CLI_ARGS}}
    dir: packages/

  ##################################################################################################

  quick:
    aliases: ["q"]
    cmds:
      - task: cc
      - task: push

  cc:
    cmds:
      - task: commit
      - task: commit

  commit:
    aliases: ["c"]
    cmds:
      - git add .
      - git commit -m "update"
    ignore_error: true

  pull:
    cmds:
      - git config pull.rebase false
      - git pull origin main

  push:
    cmds:
      - git push origin main --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git" '{print "https://github.com/"$1}'`; open $repo_url
