[project]
name = "try-jieba"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Henry.Huang", email = "hhglory@outlook.com" }
]


[tool.poetry]
name = "try-jieba"
version = "0.1.0"
description = ""
authors = ["Henry.Huang <hhglory@outlook.com>"]
readme = "README.md"
packages = [{ include = "try_jieba", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
jieba = "^0.42.1"
loguru = "^0.7.2"
typer = { extras = ["all"], version = "^0.9.0" }
beautifulsoup4 = "^4.12.2"
requests = "^2.31.0"
scikit-learn = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
