[project]
name = "try-pygwalker"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Henry.Huang", email = "hhglory@outlook.com" }]
dependencies = [
    "loguru>=0.7.2",
    "pygwalker>=0.4.7",
    "streamlit>=1.32.2",
    "gradio>=4.26.0",
    "httpx[socks]>=0.27.0",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/try_pygwalker"]


#
# scripts
#
[tool.rye.scripts]
# These three options are equivalent:
run01 = "python src/try_pygwalker/run01.py"
devserver-alt = ["flask", "run", "--app", "./hello.py", "--debug"]
devserver-explicit = { cmd = "flask run --app ./hello.py --debug" }


# lint
lint = { chain = ["lint:black", "lint:flake8"] }
"lint:black" = "black --check src"
"lint:flake8" = "flake8 src"
