version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  run:
    aliases: [ 'r' ]
    cmds:
      - rye run run01


  rye:
    cmds:
      - rye {{.CLI_ARGS}}

  add:
    aliases: [ 'a' ]
    cmds:
      - rye add {{.CLI_ARGS}}
      - rye sync -v

  lock:
    cmds:
      - rye lock -v

  add:list:
    aliases: [ 'al' ]
    cmds:
      - rye add loguru pygwalker streamlit gradio
      - rye sync -v

  sync:
    aliases: [ 's' ]
    cmds:
      - rye sync {{.CLI_ARGS}}

  venv:
    cmds:
      - rye pin 3.12 # use python 3.12
