version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  run01:
    cmds:
      - |
        poetry run python \
            src/try_selenium/run01.py

  run02:
    cmds:
      - mkdir dist/
      - |
        poetry run python \
            src/try_selenium/run02.py
    ignore_error: true

  help:
    cmds:
      - poetry run python -m selenium --help

  install:
    cmds:
      - poetry install

  add:
    cmds:
      - poetry add "typer[all]" selenium

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve
