[tool.poetry]
name = "try-spacy"
version = "0.1.0"
description = ""
authors = ["Henry.Huang <hhglory@outlook.com>"]
readme = "README.md"
packages = [{ include = "try_spacy", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
typer = { extras = ["all"], version = "^0.12.0" }
spacy = { extras = ["apple"], version = "^3.6.0" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


#
# for rye:
#
[project]
name = "try-spacy"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Henry.Huang", email = "hhglory@outlook.com" }
]
