version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  poetry:
    aliases: [ 'p', 'pm' ]
    cmds:
      - poetry {{.CLI_ARGS}} # install, update

  install:
    aliases: [ 'i' ]
    cmds:
      - poetry install

  add:
    aliases: [ 'a' ]
    cmds:
      - poetry add {{.CLI_ARGS}} # --dev

  add:all:
    aliases: [ 'aa' ]
    cmds:
      - poetry add typer[all]
      - poetry add spacy[apple] # macos + m1

  download:
    aliases: [ 'dl' ]
    cmds:
      - poetry run python -m spacy download en_core_web_sm   # english
      - poetry run python -m spacy download ja_core_news_sm  # japanese

  run:
    aliases: [ 'r' ]
    cmds:
      - poetry run python src/try_spacy/run01.py
