version: "3"

includes:
  chroma:
    taskfile: try-chroma/
    dir: try-chroma/
    optional: true

  autogpt:
    taskfile: try-autogpt/
    dir: try-autogpt/
    optional: true

  pywry:
    taskfile: try-pywry/
    dir: try-pywry/
    optional: true

  nicegui:
    taskfile: try-nicegui/
    dir: try-nicegui/
    optional: true

  pw:
    taskfile: try-playwright/
    dir: try-playwright/
    optional: true

  selenium:
    taskfile: try-selenium/
    dir: try-selenium/
    optional: true

  typer:
    taskfile: try-typer/
    dir: try-typer/
    optional: true

  spacy:
    taskfile: try-spacy/
    dir: try-spacy/
    optional: true

  ccxt:
    taskfile: try-ccxt/
    dir: try-ccxt/
    optional: true


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  install:
    cmds:
      - poetry install

  add:
    cmds:
      - poetry add click discord.py

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve
