[project]
name = "kivy-basic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "kivy[full]>=2.3.1",
    "kivymd", # "kivymd @ git+https://github.com/kivymd/KivyMD", # v2.0 master
]

[tool.uv.sources]
kivymd = { git = "https://github.com/kivymd/KivyMD" }
