version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  pkg:
    cmds:
      - rye {{ .CLI_ARGS }}

  add:
    cmds:
      - rye add kivymd --git https://github.com/kivymd/KivyMD

  run:
    aliases: [ 'r' ]
    cmds:
      - rye run python3 run0{{ .CLI_ARGS }}.py
    dir: ./src/kivy_basic

  run01:
    aliases: [ r1' ]
    cmds:
      - rye run python3 run01.py
    dir: ./src/kivy_basic

  # Button
  run02:
    aliases: [ 'r2' ]
    cmds:
      - rye run python3 run02.py
    dir: ./src/kivy_basic

  # Theme
  run03:
    aliases: [ 'r3' ]
    cmds:
      - rye run python3 run03.py
    dir: ./src/kivy_basic

  # Dialog
  run04:
    aliases: [ 'r4' ]
    cmds:
      - rye run python3 run04.py
    dir: ./src/kivy_basic
