version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  install:
    aliases: [ 'i' ]
    cmds:
      - poetry install

  poetry:
    cmds:
      - poetry {{.CLI_ARGS}} # install, update

  add:
    aliases: [ 'a' ]
    cmds:
      - poetry add {{.CLI_ARGS}}  # --dev

  add:all:
    cmds:
      - poetry add click discord.py
