version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  run:
    aliases: [ 'r' ]
    cmds:
      - poetry run python3 run.py
    dir: ./src/try_pyside

  r1:
    aliases: [ 'r1' ]
    cmds:
      - pyside6-uic themewidget.ui -o ui_themewidget.py
      - poetry run python3 run_01.py
    dir: ./src/try_pyside

  install:
    cmds:
      - poetry install

  add:
    aliases: [ 'a' ]
    cmds:
      - poetry add {{.CLI_ARGS}}  # --dev

  add:all:
    cmds:
      - poetry add flet loguru "typer[all]"

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve







