version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  install:
    aliases: [ 'i' ]
    cmds:
      - rye install weditor
      - rye sync --no-lock

  rye:
    cmds:
      - rye {{.CLI_ARGS}} # install, update

  add:
    aliases: [ 'a' ]
    cmds:
      - rye add {{.CLI_ARGS}}  # --dev

  add:dev:
    aliases: [ 'ad' ]
    cmds:
      - rye add --dev {{.CLI_ARGS}}  # --dev

  add:all:
    aliases: [ 'aa' ]
    cmds:
      #      - rye add weditor
      - poetry add uiautomator2

  run:
    aliases: [ 'r' ]
    cmds:
      - which python
      - python src/try_uiautomator2/run.py

  poetry:
    cmds:
      - echo "{{.CLI_ARGS}}"
      - poetry {{.CLI_ARGS}}

  setup:
    cmds:
      - pip install poetry
      - poetry env use 3.12.4
      - poetry env info
      #      - poetry run python -m pip install --no-cache-dir --use-pep517 lxml
      - poetry install

  run2:
    aliases: [ 'r2' ]
    cmds:
      - which python
      - python -V
      - python src/try_uiautomator2/run_02.py

  tool:
    cmds:
      - |
        uiauto.dev # source .venv/bin/activate.fish

  android:devices:
    aliases: [ 'devices', "adb", "adb:d" ]
    cmds:
      - adb devices -l

  android:packages:
    aliases: [ 'packages', 'adb:p' ]
    cmds:
      - adb shell pm list packages # 所有包
      - adb shell pm list packages -3 # 第三方包
