[project]
name = "flet-mobile-template"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "hhglory", email = "hhglory@outlook.com" }
]
dependencies = [
    "flet[all]>=0.25.2",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["."]
