version: "3"

includes:
  pywry:
    taskfile: try-pywry/
    dir: try-pywry/
    optional: true

  nicegui:
    taskfile: try-nicegui/
    dir: try-nicegui/
    optional: true

  typer:
    taskfile: try-typer/
    dir: try-typer/
    optional: true

  jieba:
    aliases: [ "j" ]
    taskfile: try-jieba/
    dir: try-jieba/
    optional: true

  django:
    aliases: [ "dj" ]
    taskfile: try-django/
    dir: try-django/
    optional: true

  faststream:
    aliases: [ "fs" ]
    taskfile: try-faststream/
    dir: try-faststream/
    optional: true

  invoke:
    aliases: [ "iv" ]
    taskfile: try-invoke/
    dir: try-invoke/
    optional: true


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  poetry:
    aliases: [ 'p' ]
    cmds:
      - poetry {{.CLI_ARGS}} # install, update
