version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  run01:
    cmds:
      - poetry run python run01.py
    dir: src/try_playwright


  install:
    cmds:
      - poetry install

  add:
    cmds:
      - poetry add "typer[all]" playwright

  i:
    cmds:
      - poetry run playwright install

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve
