version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  install:
    cmds:
      - poetry install

  add:
    cmds:
      - poetry add typer[all]
      - poetry add spacy[apple] # macos + m1

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  download:
    cmds:
      - poetry run python -m spacy download en_core_web_sm   # english
      - poetry run python -m spacy download ja_core_news_sm  # japanese

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve


  run:
    cmds:
      - poetry run python src/try_spacy/run01.py
