version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"
  SRC: "src/try_gemini"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  run:
    aliases: [ 'r' ]
    cmds:
      - echo 'google gpt api key:' ${GOOGLE_GEMINI_API_KEY}
      - poetry run python3 {{.SRC}}/run.py ${GOOGLE_GEMINI_API_KEY}

  run:note:
    cmds:
      - poetry run jupyter notebook

  install:
    cmds:
      - poetry install

  add:
    aliases: [ 'a' ]
    cmds:
      - poetry add {{.CLI_ARGS}}

  add:list:
    cmds:
      - poetry add click ccxt jupyterlab notebook ipython loguru "typer[all]"
      - poetry add pandas matplotlib seaborn plotly mplfinance

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve


