[project]
name = "try-tidevice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "facebook-wda>=1.5.0",
    "pyopenssl>=25.0.0",
    "pysocks>=1.7.1",
    "tidevice>=0.12.9",
    "typer>=0.9.4",
]
