[project]
name = "try-tidevice"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Henry.Huang", email = "hhglory@outlook.com" }
]
dependencies = [
    "tidevice[openssl]==0.12.9",
    "facebook-wda>=1.4.7",
    "tidevice3>=0.11.3",
    "urllib3==1.21.1",
    "uiautodev<=0.3.7",
    "poetry<=1.8.2",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/try_tidevice"]


[tool.poetry]
name = "try-typer"
version = "0.1.0"
description = ""
authors = ["Henry.Huang <hhglory@outlook.com>"]
readme = "README.md"
packages = [{ include = "try_tidevice", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
typer = { extras = ["all"], version = "^0.9.0" }
tidevice = { version = "0.12.9", extras = ["openssl"] }
facebook-wda = "^1.4.7"


#[build-system]
#requires = ["poetry-core"]
#build-backend = "poetry.core.masonry.api"
