[project]
name = "try-pyo3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "libpyo3",
]

[dependency-groups]
dev = [
    "maturin>=1.8.3",
]

[tool.uv.sources]
libpyo3 = { path = "libpyo3" }
