version: "3"

tasks:
  uv:
    aliases: ["pm", "pkg"]
    cmds:
      - uv {{.CLI_ARGS}}

  sync:
    aliases: ["s"]
    cmds:
      - uv sync --all-packages --all-groups

  run:
    aliases: ["r"]
    cmds:
      - uv run {{.CLI_ARGS}}
    dir: src/

  new:lib:
    aliases: ["n"]
    cmds:
      - uv run maturin new --mixed --src {{.CLI_ARGS}} # pyrslib, o3lib

  build:pyo3:
    aliases: ["b"]
    cmds:
      - uv run maturin develop --release
      # - uv run maturin build
    dir: libpyo3/

  clean:
    aliases: ["cl"]
    cmds:
      # 删除 .so 文件
      - find libpyo3/src -name "*.so" -exec rm {} \;

  run01:
    aliases: ["r1"]
    cmds:
      - uv run src/main.py

  run02:
    aliases: ["r2"]
    cmds:
      - uv run src/main.py
    dir: libpyo3/
