version: "3"

tasks:
  uv:
    aliases: ["pm", "pkg"]
    cmds:
      - uv {{.CLI_ARGS}}

  sync:
    aliases: ["s"]
    cmds:
      - uv sync --all-packages --all-groups

  run:
    aliases: ["r"]
    cmds:
      - uv run {{.CLI_ARGS}}
    dir: src/

  new:lib:
    aliases: ["n"]
    cmds:
      - uv run maturin new --mixed --src {{.CLI_ARGS}} # pyrslib, o3lib
