version: "3"

includes:
  tidevice:
    aliases: [ "td" ]
    taskfile: try-tidevice/
    dir: try-tidevice/
    optional: true

  weditor:
    aliases: [ "we" ]
    taskfile: try-weditor/
    dir: try-weditor/
    optional: true

  uiautomator2:
    aliases: [ "ua2" ]
    taskfile: try-uiautomator2/
    dir: try-uiautomator2/
    optional: true

  uiautodev:
    aliases: [ "uiauto", "ua" ]
    taskfile: try-uiautodev/
    dir: try-uiautodev/
    optional: true

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  hello:
    cmds:
      - echo hello

  setup:
    cmds:
      - pyenv update
      - pyenv install --list | grep 3.12
      - pyenv install 3.12.3

  env:
    cmds:
      - rye -h
      - rye toolchain list
      - python -v
