[project]
name = "try-gateio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.10.11",
    "asciimatics>=1.15.0",
    "gate-api>=4.83.0",
    "gate-ws>=0.3.1",
    "sortedcontainers>=2.4.0",
]
