version: "3"

includes:
  ccxt:
    aliases: [ "cc" ]
    taskfile: try-ccxt/
    dir: try-ccxt/
    optional: true

  hftbacktest:
    aliases: [ "hft" ]
    taskfile: try-hftbacktest/
    dir: try-hftbacktest/
    optional: true

  vnpy:
    aliases: [ "vn" ]
    taskfile: try-vnpy/
    dir: try-vnpy/
    optional: true

  gm:
    aliases: [ "gm" ]
    taskfile: try-gm/
    dir: try-gm/
    optional: true

  gate:
    aliases: [ "gateio" ]
    taskfile: try-gateio/
    dir: try-gateio/
    optional: true

  binance:
    aliases: [ "bn" ]
    taskfile: try-binance/
    dir: try-binance/
    optional: true
