version: "3"

includes:
  ccxt:
    aliases: [ 'cc' ]
    taskfile: try-ccxt/
    dir: try-ccxt/
    optional: true

  gate:
    aliases: [ 'gatews' ]
    taskfile: try-gatews/
    dir: try-gatews/
    optional: true

