version: "3"

includes:
  ccxt:
    aliases: [ 'cc' ]
    taskfile: try-ccxt/
    dir: try-ccxt/
    optional: true

  gate:
    aliases: [ 'gateio' ]
    taskfile: try-gateio/
    dir: try-gateio/
    optional: true

  binance:
    aliases: [ 'bn' ]
    taskfile: try-binance/
    dir: try-binance/
    optional: true
