[tool.poetry]
name = "try-ccxt"
version = "0.1.0"
description = ""
authors = ["Henry.Huang <hhglory@outlook.com>"]
readme = "README.md"
packages = [{ include = "try_ccxt", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
ccxt = "^4.1.75"
jupyterlab = "^4.0.9"
ipython = "^8.18.1"
notebook = "^7.0.6"
loguru = "^0.7.2"
typer = { extras = ["all"], version = "^0.9.0" }
pandas = "^2.1.3"
matplotlib = "^3.8.2"
seaborn = "^0.13.0"
plotly = "^5.18.0"
mplfinance = "^0.12.10b0"  # k 线图
peewee = "^3.17.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
