[project]
name = "try-ccxt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ccxt>=4.4.61",
    "ipython>=8.32.0",
    "jupyterlab>=4.3.5",
    "loguru>=0.7.3",
    "matplotlib>=3.10.0",
    "mplfinance>=0.12.10b0",
    "notebook>=7.3.2",
    "pandas>=2.2.3",
    "peewee>=3.17.9",
    "plotly>=6.0.0",
    "seaborn>=0.13.2",
]
