[tool.poetry]
name = "try-nicegui"
version = "0.1.0"
description = ""
authors = ["Henry.Huang <hhglory@outlook.com>"]
readme = "README.md"
packages = [{include = "try_nicegui", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
nicegui = "^1.2.17"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
