[tool.poetry]
name = "try-nicegui"
version = "0.1.0"
description = ""
authors = ["Henry.Huang <hhglory@outlook.com>"]
readme = "README.md"
packages = [{include = "try_nicegui", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10,<3.12"
click = "^8.1.3"
pystray = "^0.19.4"
loguru = "^0.7.0"
pillow = "^8.3.2"
nicegui = "^1.2.17"
pywebview = "^4.1"


[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
