version: "3"

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:

  run:
    cmds:
      - |
        python src/try_nicegui/main.py

  run:tray:
    cmds:
      - |
        python src/try_nicegui/run01_tray.py

  install:
    cmds:
      - poetry install

  add:
    cmds:
      - poetry add click nicegui pystray loguru Pillow

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve
