version: "3"

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################

tasks:
  run:
    cmds:
#      - source $(poetry env info --path)/bin/activate
      - |
        python src/try_nicegui/run02_tpl.py --mode=native
#      - deactivate

  run3:
    cmds:
#      - source $(poetry env info --path)/bin/activate
      - |
        python3 src/try_nicegui/run03_exe.py
#      - source $(poetry env info --path)/bin/activate

  run:tray:
    cmds:
      - |
        python src/try_nicegui/run01_tray.py

  run:exe:
    cmds:
      - ./dist/myapp

  clean:
    cmds:
      - rm -rf dist/
      - rm -rf build/
      - rm -rf .venv/
      - poetry env remove --all
    ignore_error: true

  release:
    cmds:
      #      - poetry run pyinstaller -F -w -i ./public/images/logo.ico \
      #        src/try_nicegui/run02_tpl.py \
      #        --name myapp
      #      - cp poetry.toml poetry.bak.toml
      #      - cp poetry.rel.toml poetry.toml
      - poetry install --directory=.
      - poetry run python build.py
      #      - cp poetry.bak.toml poetry.toml
      - open ./dist

  ################################################################################################

  debug:
    cmds:
      #      - poetry shell -vvv
      - poetry debug info
      - poetry env list

  env:fix:
    cmds:
      #      - rm -rf ~/Library/Caches/pypoetry  # 也不要乱删此路径
      - poetry env list
      - poetry env remove --all
      - poetry config virtualenvs.path --unset  # 不要改此参数

  env:init:
    cmds:
      - pyenv which python3
      - poetry env use $(pyenv which python3)
      - task: debug
      #      - poetry env use $(pyenv which python3)
      #      - poetry env use /Users/dev/.pyenv/versions/py310-exe/bin/python3
#      - poetry env use 3.10
    ignore_error: true

  env:cfg:
    cmds:
      - poetry config virtualenvs.in-project false
      - poetry config virtualenvs.create false
      - poetry config virtualenvs.prefer-active-python true
      - poetry config virtualenvs.path .venv
      - poetry config --list

  install:
    cmds:
      #      - poetry config virtualenvs.in-project true
      #      - poetry config virtualenvs.create true
      #      - poetry config virtualenvs.prefer-active-python true
      #      - poetry config virtualenvs.path .venv
      - poetry install -vvv
      - poetry run pip3 install numpy
    ignore_error: true

  add:
    cmds:
      - poetry add click nicegui pystray loguru Pillow
      - |
        poetry run \
          pip3 install numpy # fix for m1 mac

  add:dev:
    cmds:
      - |
        poetry add --dev \
          pyinstaller

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve
