version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  run:
    aliases: [ 'r' ]
    cmds:
      - task: ra

  docs:
    cmds:
      - open "http://127.0.0.1:8000/docs"

  pdm:
    aliases: [ 'pm', "p", "pkg" ]
    cmds:
      - pdm {{.CLI_ARGS}}

  poetry:
    cmds:
      - poetry {{.CLI_ARGS}}

  rye:
    cmds:
      - rye {{.CLI_ARGS}} # install, update

  add:list:
    aliases: [ 'a' ]
    cmds:
      #      - rye add weditor
      - pdm add fastapi "uvicorn[standard]" sqlmodel
      - pdm add loguru
      - pdm add fastapi_amis_admin[sqlmodel] aiosqlite greenlet
      - pdm add --dev isort pytest mypy ruff
