version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  run:
    aliases: [ 'r' ]
    cmds:
      - task: ra

  run:sub:
    aliases: [ 'rs', 'sub' ]
    cmds:
      - faststream run run_sub:app --reload {{.CLI_ARGS}}  # --workers 2
    dir: src/try_faststream/

  run:pub:
    aliases: [ 'rp', 'pub' ]
    cmds:
      - python run_pub.py
    dir: src/try_faststream/

  run:pub:cron:
    aliases: [ 'rc', 'cron', 'pub:cron' ]
    cmds:
      - taskiq scheduler run_pub_cron:scheduler
    dir: src/try_faststream/

  run:pub:cron2:
    aliases: [ 'rc2', 'cron2', 'pub:cron2' ]
    cmds:
      - python run_pub_cron.py
    dir: src/try_faststream/



  docs:
    cmds:
      - open "http://127.0.0.1:8000/docs"

  pdm:
    aliases: [ 'pm', "p", "pkg" ]
    cmds:
      - pdm {{.CLI_ARGS}}

  poetry:
    cmds:
      - poetry {{.CLI_ARGS}}

  rye:
    cmds:
      - rye {{.CLI_ARGS}} # install, update

  add:list:
    aliases: [ 'a' ]
    cmds:
      #      - rye add weditor
      - pdm add fastapi "uvicorn[standard]" sqlmodel
      - pdm add loguru pydantic-settings
      - pdm add faststream[nats] taskiq taskiq-nats taskiq-redis taskiq-faststream
      - pdm add fastapi_amis_admin[sqlmodel] aiosqlite greenlet
      - pdm add --dev isort pytest mypy ruff watchfiles
