version: "3"

includes:
  pyecharts:
    aliases: ["pc"]
    taskfile: try-pyecharts/
    dir: try-pyecharts/
    optional: true

  matplotlib:
    aliases: ["mplot", "mp"]
    taskfile: try-matplotlib/
    dir: try-matplotlib/
    optional: true

  plotly:
    aliases: ["pl"]
    taskfile: try-plotly/
    dir: try-plotly/
    optional: true
