[project]
name = "try-duckdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.2.0",
    "faker>=37.0.0",
    "jupyterlab>=4.3.5",
    "notebook>=7.3.2",
    "pandas>=2.2.3",
    "polars>=1.23.0",
    "pyarrow>=19.0.1",
]
