version: "3"

tasks:
  uv:
    aliases: [ "pm", "pkg" ]
    cmds:
      - uv {{.CLI_ARGS}}

  run:
    aliases: [ 'r' ]
    cmds:
      - uv run {{.CLI_ARGS}}
    dir: src/

  install:
    aliases: [ 'i' ]
    cmds:
      - brew install ta-lib  # fix: https://github.com/TA-Lib/ta-lib-python/issues/418#issuecomment-826129619
      - export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
      - export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
      - uv add ta-lib numpy
      - uv add vnpy vnpy_ctastrategy vnpy_ctabacktester vnpy_datamanager vnpy_sqlite vnpy_rqdata
      - uv add vnpy_ctp
